Update sveltekit-authentication-using-cookies.md
Error: invalid(...) is now fail(...)
Svelte changed the 'invalid' function to 'fail' in '@sveltejs/kit' form validation. I've changed the code respectively. Please review and test.
Now in the official doc: https://kit.svelte.dev/docs/form-actions
Didn't found the changelog for this change in the svelte docs.